name: luxury_real_estate_flutter_ui_kit
description: "Luxury Real Estate App Flutter UI Kit"
publish_to: 'none'
# Flutter Version: 3.22.1
# Dart Version: 3.4.1
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  pinput: ^4.0.0
  google_maps_flutter: ^2.2.8
  visibility_detector: ^0.4.0+2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.3
  http: ^1.3.0
  html_unescape: ^2.0.0
  google_maps_cluster_manager: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: fonts/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: fonts/Inter-Bold.ttf
